spring:
  application:
    name: api
  mvc:
    async:
      request-timeout: 10s
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=5000,expireAfterAccess=24h
    cache-names:
      - anime-relations
      - principal-anime

server:
  port: ${PORT:8080}
  shutdown: graceful
  compression:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: never

mal:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
