spring:
  config:
    activate:
      on-profile: prod

cors:
  allowed-origins:
    - https://miruhq.com
    - chrome-extension://pikhegpinigblbcgdpahppenpinfohom

logging:
  level:
    root: INFO

app:
  oauth-url: https://www.miruhq.org
  backend-url: https://miruhq-api.onrender.com
