spring:
  config:
    activate:
      on-profile: dev

cors:
  allowed-origins:
    - http://localhost:4200
    - chrome-extension://eoeekjllkilpkcafhodpaicjihccfofj

logging:
  level:
    root: INFO
    com.marcelmalewski.miruhqapi: DEBUG

app:
  oauth-url: http://localhost:4200
  backend-url: http://localhost:8080
